### PR TITLE
pull upstream@2.4

### PR DESCRIPTION
**Pull request by sndrs**
pulls the upstream changes up to current main (2.4) and tags main accordingly

### CODE REVIEW

**Review by SiAdcock — APPROVED** [review]
Let\'s Get tHis Merged 🚢

**Comment by jamie-lynch** [comment]
I ran [Licensed](https://github.com/github/licensed) locally to update the cached license files. There were three that were parsed as `"other"` but on further investigation they're under either MIT or BSD-3-Clause licenses so I've added them to the reviews array in the config to mark them as manually checked and okay.

**Comment by sndrs** [comment]
i've added it to https://github.com/guardian/source-shakedown and it looks good – caching is also super fast

**Review by SiAdcock — APPROVED** [review]
Great work, thanks @sndrs and @jamie-lynch!

**Comment by sndrs** [comment]
pushed these changes to https://github.com/actions/setup-node/pull/239

**Pull request merged**
